---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-registry
  labels:
    name: nifi-registry
    app: nifi-registry
  annotations:
    app.kubernetes.io/name: nifi-registry
    app.kubernetes.io/part-of: nifi
spec:
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: Always
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: wait-for-zookeeper
          image: docker.io/busybox:1.35
          command:
          - sh
          - -c
          - |
            echo "Connecting to Zookeeper ${NIFI_ZK_CONNECT_STRING}"
            until nc -vzw 1 zookeeper 2181 ; do
              echo "Waiting for zookeeper to start"
              sleep 3
            done
          envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
          resources:
            requests:
              cpu: 20m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
      - name: nifi-registry
        image: docker.io/apache/nifi-registry:1.20.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18080
        env:
          - name: NIFI_REGISTRY_WEB_HTTP_PORT
            value: "18080"
        envFrom:
          - configMapRef:
              name: nifi-cm
              optional: false
        livenessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 400m
            memory: 1Gi
          limits:
            cpu: 400m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - ALL
      volumes:
        - name: nifi-registry
          emptyDir:
            sizeLimit: 3Gi
